Step3
code-squad/java-racingcar pull request #168
Opened 2018-03-07 04:33 UTC by david-learner

add makeCar, rank method in Racing class.
add InputView, ResultView, Car Class.

2018-03-07 18:19 UTC, javajigi requested changes
구현하느라 수고했네요. 피드백 남겼어요.

2018-03-07 18:19 UTC, javajigi commented on src/main/java/racingcar/Car.java
> +	public void setPosition(int position) {
set 메소드를 쓰지 않고 구현해 본다.

2018-03-07 18:19 UTC, javajigi commented on src/main/java/racingcar/Racing.java
> +	private Car[] registeredCar;
두 개의 값은 중복된 값이다.
registeredCar 인스턴스 변수만 유지하도록 구현한다.

2018-03-07 18:19 UTC, javajigi commented on src/main/java/racingcar/Racing.java
> +	private Car[] registeredCar;
Racing 인스턴스를 생성할 때 registeredCarNames를 전달해 registeredCar 배열을 생성하도록 개선해 본다.

2018-03-07 18:19 UTC, javajigi commented on src/main/java/racingcar/Racing.java
> +		this.registeredCar[index].setPosition(position);
Car의 상태를 변경(position 변경)하는 구현을 Car 외부가 아니라 Car가 담당하도록 한다.

2018-03-07 18:19 UTC, javajigi commented on src/main/java/racingcar/Racing.java
> +		return winners;
메소드가 하는 일이 너무 많다. 한 가지 일만 하도록 개선한다.
indent 깊이도 너무 깊다. indent 깊이를 줄인다.

2018-03-08 06:49 UTC, david-learner commented on src/main/java/racingcar/Car.java
> +	public void setPosition(int position) {
set 제거하고,  Car클래스 내에 move메소드를 추가하여 Car객체에서 position이 조절되게 했습니다.

2018-03-08 06:51 UTC, david-learner commented on src/main/java/racingcar/Racing.java
> +	private Car[] registeredCar;
생성할 때 InputView로부터 자동차 이름들을 받아서 registerdCarNames배열에 저장하여 makeCar()의 인자로 넣어 Car객체가 생성되게 했습니다.

2018-03-08 06:55 UTC, david-learner commented on src/main/java/racingcar/Racing.java
> +		return winners;
메소드를 하나 빼서 줄이긴 헀는데, compare()의 매개변수 개수가 많아 어떻게 줄일지 고민입니다.

2018-03-08 07:12 UTC, merged