Junit Test
code-squad/java-racingcar pull request #184
Opened 2018-03-11 02:47 UTC by JosephChun

junit test

2018-03-11 03:47 UTC, javajigi commented
내일 junt 관련 강의를 들은 후 개선해 보면 좋겠네요.

2018-03-11 05:27 UTC, JosephChun commented
예 감사합니다.

2018-03-12 03:31 UTC, javajigi requested changes
오늘 수업 중 피드백한 내용 반영해 보세요.

2018-03-12 03:31 UTC, javajigi commented on src/main/java/racingcar/CarRaceTest.java
> +    }
CarMoveTest, CarNotMoivng 메소드는 CarTest 추가해 구현하는 것이 맞겠음.

2018-03-12 03:31 UTC, javajigi commented on src/main/java/racingcar/CarRaceTest.java
> +    }
수업 시간 피드백 반영해 개선해 본다.

2018-03-12 03:31 UTC, javajigi commented on src/main/java/racingcar/CarRaceTest.java
> +        cars.getCars().get(1).go(7);
get()을 계속해서 연속해 사용하는 것을 비추

2018-03-12 03:31 UTC, javajigi commented on src/main/java/racingcar/CarRaceUtill.java
> +    }
CarRaceUtill 클래스에 대한 테스트 메소드도 추가해 보면 좋겠네요.
현재 인스턴스 메소드로 구현하고 있는데 클래스 메소드로 변경하고 반환 값을 받도록 개선해 보세요.

2018-03-12 07:29 UTC, merged