자동차경주게임: 1단계
code-squad/java-racingcar pull request #209
Opened 2018-03-31 12:25 UTC by iamkyu

2018-03-31 22:15 UTC, javajigi requested changes
구현 잘 했네요. 객체간의 관계를 RacingGame에 집중했는데요. 분산할 방법을 찾아보면 좋을 것 같아요.

2018-03-31 22:15 UTC, javajigi commented on src/main/java/race/Drawer.java
> +    private String format = "-";
상수 값 convention을 따라라.
상수 값은 static final로 구현하면 변수 이름을 모두 대문자로 구현하는 것이 관례이다.

2018-03-31 22:15 UTC, javajigi commented on src/main/java/race/Main.java
> +        int iteration = scanner.nextInt();
View 관련 로직도 별도의 클래스로 분리하면 좋을 것 같아요.

2018-03-31 22:15 UTC, javajigi commented on src/main/java/race/MoveRule.java
> +        return randomValue >= 4;
값을 하드코딩하지 마라.
상수(static final)를 만들고 이름을 부여해 이 변수의 역할이 무엇인지 의도를 드러내라.

2018-03-31 22:15 UTC, javajigi commented on src/main/java/race/MoveRule.java
> +    boolean canMove(int randomValue);
인터페이스 추가 👍

2018-03-31 22:15 UTC, javajigi commented on src/main/java/race/Car.java
> +    void move() {
메소드 인자로 MoveRule을 인자로 받아 구현하는 것은 어떤가요?

2018-03-31 22:15 UTC, javajigi commented on src/main/java/race/RacingGame.java
> +    private Random random;
인스턴스 변수가 너무 많다. 인스턴스 변수를 줄여본다.
객체지향 설계 원칙의 "규칙 7: 3개 이상의 인스턴스 변수를 가진 클래스를 쓰지 않는다." 원칙을 따라본다. 즉, 2개까지 허용한다.

2018-03-31 22:15 UTC, javajigi commented on src/test/java/race/DrawerTest.java
> +}
View에 대한 테스트는 어려워 요구하지 않는데 💯

2018-04-01 02:53 UTC, iamkyu commented
@javajigi 
리뷰 감사합니다. 다음과 같은 내용을 반영했습니다.

- 매직넘버를 상수로 변경
- 일부 상수 값 Convention에 따라 변수명 변경
- RaceGame에 집중되어 있는 객체 관계를 나누는 과정에서 일부 클래스 추가됨 (GameResult, Recorder)
- GameView 클래스 추가
- 리팩토링 과정에서 일부 용어를 변경 
    - Car -> RaceCar
    - iteration -> labs
    - MoveRule -> RaceRule

2018-04-01 09:05 UTC, merged