자동차 경주 게임 1단계
code-squad/java-racingcar pull request #212
Opened 2018-03-31 15:25 UTC by pkgonan

[목표]
* 초간단 자동차 경주 게임을 구현한다.
* 주어진 횟수 동안 n대의 자동차는 전진 또는 멈출 수 있다.
* 사용자는 몇 대의 자동차로 몇 번의 이동을 할 것인지를 입력할 수 있어야 한다.
* 전진하는 조건은 0에서 9 사이에서 random 값을 구한 후 random 값이 4이상일 경우이다.
* 자동차의 상태를 화면에 출력한다. 어느 시점에 출력할 것인지에 대한 제약은 없다.

2018-03-31 22:31 UTC, javajigi requested changes
구현 잘 했네요. 단, View 관련 로직과 핵심 로직 구현을 분리하는 연습을 하면 좋을 것 같아요.

2018-03-31 22:31 UTC, javajigi commented on src/main/java/racinggame/Main.java
> +    private static int tryCount;
클래스 변수로 구현하지 않고 method local 변수로 만들어 구현한다.

2018-03-31 22:31 UTC, javajigi commented on src/main/java/racinggame/RacingGame.java
> +    private final static String STRING_FORMAT = "-";
하드코딩하지 않고 상수 값으로 구현 👍

2018-03-31 22:31 UTC, javajigi commented on src/main/java/racinggame/RacingGame.java
> +            throw new IllegalArgumentException();
생성자에서 예외처리 👍

2018-03-31 22:31 UTC, javajigi commented on src/main/java/racinggame/Car.java
> +    void move() {
이 메소드에서 random 값을 인자로 전달하는 것은 어떤가요?

2018-03-31 22:31 UTC, javajigi commented on src/main/java/racinggame/RacingGame.java
> +    }
핵심 로직을 구현하는 부분(상태 변경 등과 같은)과 View 로직(System.in을 통해 값 입력, System.out을 통해 값 출력)을 분리한다.
한 객체에 이 두 가지 로직이 같이 구현되어 있는 경우 추후 View가 되었을 때 핵심 로직을 구현하는 코드를 재사용할 수 없다.
또한 View에 종속되는 순간 테스트하기도 힘들다. 
이 연습은 웹 프로그래밍을 할 때 DB에 종속된 코드와 DB에 종속되지 않은 코드를 분리함으로써 테스트 가능하도록 구현하는 것과 같은 연습이다.

2018-04-01 13:14 UTC, pkgonan commented on src/main/java/racinggame/Car.java
> +    void move() {
@javajigi
안녕하세요.

4이상일때 전진하는 조건 ( 전진하는 조건은 0에서 9 사이에서 random 값을 구한 후 random 값이 4이상일 경우이다.)
위 조건이 자동차 도메인의 속성이 아니라 레이싱 게임의 속성이라고 보고
랜덤값을 받아 position 값을 더할지 말지를 RacingGame안에 두었습니다.

위 메소드에서 Random값을 인자로 전달받는 것을 조언해주신 것은
RacingGame.class의 move 메소드 테스트가 용이해지는 부분 때문인가요?

2018-04-02 00:58 UTC, javajigi commented on src/main/java/racinggame/Car.java
> +    void move() {
자동차 도메인의 인스턴스 변수가 아니기 때문에 자동차의 속성으로 볼 수는 없을 것 같아요.
자동차의 move()에 대한 결정을 외부가 아니라 Car에서 하는 것이 낫지 않을까라고 생각해요.

2018-04-02 01:01 UTC, javajigi requested changes
핵심 로직과 View 로직 분리와 관련해 피드백 하나 남겼어요.

2018-04-02 01:01 UTC, javajigi commented on src/main/java/racinggame/Main.java
> +            racingGame.printRacingResult();
racingGameView을 RacingGame에 인자로 전달하기보다 start() 메소드를 실행하고 이동 결과를 반환한 후 반환 결과를 racingGameView에 전달해 구현하면 어떨까요?

racingGameView을 RacingGame에 전달하면 핵심 로직과 View로직이 결합되는 구조가 된다고 생각하는데요.

2018-04-02 01:09 UTC, pkgonan commented on src/main/java/racinggame/Main.java
> +            racingGame.printRacingResult();
오..
놓치고 있던 부분인데 감사합니다!!

2018-04-02 11:57 UTC, merged