Step0, Step1
code-squad/java-racingcar pull request #217
Opened 2018-04-01 12:21 UTC by jinhoyim

1. 자동차 경주는 렌더쪽을 어떻게 분리할 지 몰라서 우선 Console 프로그램 쪽에서 렌더를 하고 있습니다.

2. 시도결과에 따른 이동여부를 자동차가 판단하고 이동을 시키고 있는데, 판단에 대한 책임을 MovingValue 가 했으면 더 좋을 것 같습니다.

3. CarRacing 클래스의 생성자 쪽을 테스트 하고 싶은데, 두가지 큰 어려움이 있습니다.
생성자와 조회의 테스트를 어떻게 해야 하나요? 생성은 생성만 하고, 생성자 안에서 작업한 것에 대해서 테스트를 하려면 조회를 해야 하는데, 그럼 두개 또는 그 이상의 테스트를 해야 되네요.
또 멤버 배열에 만들고 테스트를 하는데 예를 들면 2개 만들고 [0], [1] 로 요소를 찾아와 테스트 한다고 하지만 이게 10개 이상이 되면 어떻게 검증해야 하나요? 테스트 코드에서 for 문을 돌려서 assert 를 하면 안될 것 같아서 이 부분이 궁금합니다.

4. 클래스가 인터페이스를 구현한 것도 테스트할 수 있나요?

5. 테스트 코드에 중복되는 로직을 메서드로 빼도 된다는 글을 본 적이 있는데 이 부분도 궁금합니다.

6. 테스트에 상수가 들어가는 부분들이 있는데, 실제로 클래스에서 const로 설정하고 싶은 부분들이 있는데 거기까지 작업하지 못했습니다. 예를 들면 이동하는 최소 값(4)과 최대값(9)를 const 로 설정해두려 하는데 괜찮은가요? MovingValue에 범위를 넣어서 생성해도 좋다는 생각도 드네요.

계산기와 비교해서 자동차 경주는 방어구문을 작성하는 것도 너무 어렵습니다. 디자인을 전체적으로 잘못한 것 같기도 하네요.

2018-04-01 23:13 UTC, javajigi requested changes
구현 깔끔하게 잘 하셨네요.

3. CarRacing 클래스의 생성자 쪽을 테스트 하고 싶은데, 두가지 큰 어려움이 있습니다.
생성자와 조회의 테스트를 어떻게 해야 하나요? 생성은 생성만 하고, 생성자 안에서 작업한 것에 대해서 테스트를 하려면 조회를 해야 하는데, 그럼 두개 또는 그 이상의 테스트를 해야 되네요.
또 멤버 배열에 만들고 테스트를 하는데 예를 들면 2개 만들고 [0], [1] 로 요소를 찾아와 테스트 한다고 하지만 이게 10개 이상이 되면 어떻게 검증해야 하나요? 테스트 코드에서 for 문을 돌려서 assert 를 하면 안될 것 같아서 이 부분이 궁금합니다.

> 배열을 쓰면 for문을 쓰게 되고요. List 사용해서 assertj와 같은 도구 활용해 해결할 수 있어요.

클래스가 인터페이스를 구현한 것도 테스트할 수 있나요?
> 테스트할 수 있기는 한데 굳이 테스트할 필요가 있을까요?

테스트 코드에 중복되는 로직을 메서드로 빼도 된다는 글을 본 적이 있는데 이 부분도 궁금합니다.
> 맞습니다. 테스트 코드 중복도 제거하는 것이 좋고요. 메소드로 분리해야 합니다.

2018-04-01 23:13 UTC, javajigi commented on src/main/java/com/codesquad/calculator/StringCalculator.java
> +    }
계산기 구현 👍

2018-04-01 23:13 UTC, javajigi commented on src/main/java/com/codesquad/carracing/Car.java
> +        return value >= 4 && value < 10;
값을 하드코딩하지 마라.
상수(static final)를 만들고 이름을 부여해 이 변수의 역할이 무엇인지 의도를 드러내라.

2018-04-01 23:13 UTC, javajigi commented on src/main/java/com/codesquad/carracing/Car.java
> +    public void move(final MovingValue movingValue) {
`boolean isMovable()`과 같은 메소드를 가지는 MoveStrategy와 같은 인터페이스를 추가하고 이 인터페이스를 구현하는 RandomMoveStrategy와 같은 구조로 하면 어떨까요?

2018-04-01 23:13 UTC, javajigi commented on src/main/java/com/codesquad/carracing/CarRacing.java
> +    final Car[] cars;
배열 보다는 List collection 사용해 구현하면 어떨까요?

2018-04-01 23:13 UTC, javajigi commented on src/main/java/com/codesquad/carracing/CarRacing.java
> +            throw new IllegalArgumentException("1번 이상의 시도 횟수가 필요합니다.");
생성자에서 유효성 체크 💯

2018-04-01 23:13 UTC, javajigi commented on src/main/java/com/codesquad/carracingapp/ConsoleCarRacingApp.java
> +        final int numberOfTries = Integer.parseInt(inputNumberOfTries);
사용자 값을 입력 받는 부분을 InputView와 같은 클래스로 분리하는 것은 어떨까요?

2018-04-01 23:13 UTC, javajigi commented on src/main/java/com/codesquad/carracingapp/ConsoleCarRacingApp.java
> +    private static void printCars(final Car[] cars) {
결과를 출력하는 부분도 ResultView와 같이 분리하는 것은 어떨까요?

2018-04-01 23:13 UTC, javajigi commented on src/test/java/com/codesquad/carracing/CarTest.java
> +        assertThat(position).isEqualTo(0);
테스트 👍

2018-04-02 12:11 UTC, jinhoyim commented on src/main/java/com/codesquad/carracing/Car.java
> +    public void move(final MovingValue movingValue) {
MovingValue 라고 이상하게 이름을 지었지만... 말씀하신 것을 염두해뒀었어요. 이런게 전략패턴이군요!

2018-04-04 15:34 UTC, jinhoyim commented
OutputView 와 InputModel, CarRacing 및 OutputModel 은 금요일에나 진행할 수 있을 것 같아요.

2018-04-04 23:53 UTC, jinhoyim commented
Console 의 Reader, Writer는 함께 사용되는 경우가 많아서 둘을 하나로 합치는게 좋을것 같네요.

2018-04-05 04:42 UTC, javajigi requested changes
interface를 만들고 역할을 분리하는 것은 좋은데 너무 복잡한 것은 아닌가 라는 느낌이 드네요. 다음과 같은 수준이어도 충분하지 않을까요?

```
public static void main(String[] args) {
    int carNo = InputView.getCarNo();
    int tryNo = InputView.getTryNo();

    MoveStrategy strategy = new RandomMoveStrategy();
    RacingGame racingGame = new RacingGame(carNo);
    for(int i = 0; i < tryNo; i++) {
        GameResult result = racingGame.move(strategy);
        ResultView.print(result);
    }
}
```

지금 단계에서는 View에 대한 테스트 코드 구현보다는 도메인 로직과 View 로직을 분리하는 것에 집중해 보면 좋을 것 같아요.

2018-04-05 04:42 UTC, javajigi commented on src/main/java/com/codesquad/carracing/RandomMoveStrategy.java
> +
return generatedNumber >= MOVABLE_MIN && generatedNumber <= MOVABLE_MAX ;

위와 같이 한 줄로 구현할 수 있지 않을까요?

2018-04-05 05:12 UTC, jinhoyim commented
네 뷰쪽은 어느정도 생략해보도록 하겠습니다.

2018-04-08 10:49 UTC, merged