RacingCar Step1 입니다. 코드리뷰 부탁드립니다.
code-squad/java-racingcar pull request #220
Opened 2018-04-01 15:30 UTC by devFrankle

코드 리뷰 부탁드립니다. 
교수님 밑에 힌트 내용을 못보고 짜서,  우선 드리는데 내일 다시 한번 짜보겠습니다!
그럼 수고하세요!
감사합니다.

2018-04-02 04:35 UTC, javajigi requested changes
클래스 하나에서 구현하지 말고 클래스를 분리해 보면 좋을 것 같아요.
도메인 로직과 View 로직을 분리하는 것에 집중해 도전해 보면 좋겠어요.

2018-04-02 14:17 UTC, devFrankle commented
교수님 힌트보고, 분리한다고 생각해서 해봤는데 코드리뷰 부탁드립니다. 
감사합니다.

2018-04-02 21:40 UTC, javajigi requested changes
구현하느라 수고하셨어요.

도메인 로직과 View 로직을 구분하기 위해 다음과 같은 구조로 도전해 보면 어떨까요?

```
public static void main(String[] args) {
    int carNo = InputView.getCarNo();
    int tryNo = InputView.getTryNo();

    RacingGame racingGame = new RacingGame(carNo);
    for(int i = 0; i < tryNo; i++) {
        GameResult result = racingGame.move();
        ResultView.print(result);
    }
}
```

GameResult에 이동한 위치 정보가 포함되어 있고요. 이 위치 정보를 활용해 출력하는 구조로 구현해 보면 좋을 것 같아요.

2018-04-03 13:39 UTC, devFrankle commented
안녕하세요? 교수님 메일 주신대로, 코드를 변경해서 구조를 바꿔봤는데, 코드리뷰 부탁드립니다.
감사합니다.

2018-04-03 13:45 UTC, merged