자동차경주게임: 2단계
code-squad/java-racingcar pull request #221
Opened 2018-04-02 02:08 UTC by iamkyu

- 각 자동차에 이름을 부여할 수 있다. 전진하는 자동차를 출력할 때 자동차 이름을 같이 출력한다.
- 자동차 이름은 쉼표(,)를 기준으로 구분한다.
- 자동차 경주 게임을 완료한 후 누가 우승했는지를 알려준다. 우승자는 한명 이상일 수 있다.

2018-04-02 05:22 UTC, javajigi requested changes
Map 사용으로 인해 구현과 테스트 코드 또한 복잡해지는 느낌이 드네요. 좀 더 단순한 구조 고민해 보면 어떨까요?

List<RaceCar>를 가지는 RaceCars를 추가한다면 좀 더 깔끔하게 구현할 수 있을까요?

2018-04-02 05:22 UTC, javajigi commented on src/main/java/race/GameResult.java
> +        return winners;
winners를 인스턴스 변수로 구현하지 말고 이 메소드를 호출하는 시점에 decideWinners()를 호출해 반환하는 것은 어떨까?

2018-04-02 05:22 UTC, javajigi commented on src/main/java/race/GameResult.java
> +    private Map<String, Recorder> records;
Map을 쓰니까 key와 값을 꺼내는데 불편한 점이 있는데 다른 방법은 없을까?

2018-04-02 05:22 UTC, javajigi commented on src/test/java/race/RecorderTest.java
> +        Assert.assertArrayEquals(expected.toArray(), recorder.getRecords().toArray());
assertj 한번 적용해 보면 어떨까?
이번 기회에 모든 테스트 코드를 assertj 활용해 구현해 본다.

2018-04-02 05:22 UTC, javajigi commented on src/test/java/race/RaceCarTest.java
> +        raceCar.move(alwaysFalseRule);
굳이 3회 반복할 필요가 있나?

2018-04-02 23:35 UTC, iamkyu commented
@javajigi 리뷰 감사합니다.
코드 작성하면서도 현재 자료구조가 다루기 어렵다라고 생각했었는데 개선하려고 충분히 고민 못한게 부끄럽네요.
사실 자바8에 익숙치가 않아서 최초 구현때는 `List`를 `stream`해서는 원하는 구조를 만들 수 없겠다고 생각했는데,
`Map`으로 구현 해보는 과정에서 연습이 된 덕에 `List`로 좀 더 수월하게 바꿀 수 있었던 것 같습니다.
다음과 같은 내용 반영했습니다.

- 일부 자료 구조 변경
- 모든 단위 테스트를 AssertJ를 사용하도록 변경
- 사소한 리팩토링

2018-04-03 08:53 UTC, javajigi requested changes
merge하려다 궁금해서 질문 남기는데요. Test 코드에서 static method를 직접 쓰지 않고 Assertions.assertEquals()와 같이 구현하는 이유가 있나요?

2018-04-03 10:42 UTC, iamkyu commented
@javajigi 
딱히 의도를 가진건 아니였습니다.
IntelliJ에서 최초 `assertThat()`을 입력할 때 import를 제안 안해주거나 제안해줘도 너무 많은 후보를 보여줘서 차라리 자동완성+직접입력으로 하는게 더 편하다고 느껴서 최근 그렇게 하고 있었습니다.

혹시 코드를 읽는데 가독성을 떨어뜨리거나 방해가 되신다면 static import 하도록 하겠습니다!

2018-04-03 11:41 UTC, javajigi commented
@iamkyu 
아닙니다. 특별히 다른 이유가 있는지 궁금해서 질문 남겼어요.

2018-04-03 11:41 UTC, merged