Step2
code-squad/java-racingcar pull request #222
Opened 2018-04-02 12:13 UTC by hello-sangsik

- Car name 속성 추가
- UserRecord 추가
- ConsoleMain display 로직 분리
- 우승자 선정 로직 추가

게임기록의 자료구조를 고민했는데 만족할만한 답을 찾지 못했습니다.
그래서 우승자 선정하는 로직도 지나치게 복잡해지고 테스트 케이스 작성이 잘 안된것 같습니다.
피드백 받고 좀더 리팩토링 해보겠습니다.

2018-04-02 12:57 UTC, javajigi requested changes
도메인 로직과 View 로직을 구분하기 위해 한번 시도할 때마다의 출력 결과를 모두 기록하고 있는데요.
출력 결과를 모두 기록하지 말고 다음과 같이 구현하는 것은 어떨까요?

```
public static void main(String[] args) {
    int carNo = InputView.getCarNo();
    int tryNo = InputView.getTryNo();

    RacingGame racingGame = new RacingGame(carNo);
    GameResult result;
    for(int i = 0; i < tryNo; i++) {
        result = racingGame.move();
        ResultView.print(result);
    }
    ResultView.printWinner(result);
}
```

이렇게 구현하면 GameResult는 List<Car> 정보만 가지고 있으면 되고, 우승자에 관련한 로직은 GameResult에서 List<Car> 정보를 활용해 구현하면 어떨까요?

2018-04-03 02:33 UTC, javajigi requested changes
구현 깔끔하게 잘 했네요. step2 마지막 피드백이 될 것 같아요.

2018-04-03 02:33 UTC, javajigi commented on src/main/java/racingcar/GameResult.java
> +        return winners;
메소드가 너무 많은 일을 하고 있다. 다음 원칙을 지켜 메소드를 구현한다.

작게 만들어라. - 함수를 만드는 첫 번재 규칙은 '작게'다. 함수를 만드는 두 번째 규칙은 '더 작게'다.
한 가지만 해라. - 함수는 한 가지를 해야 한다. 그 한 가지를 잘 해야 한다. 그 한 가지만 해야 한다.

2018-04-03 02:33 UTC, javajigi commented on src/main/java/racingcar/GameResult.java
> +            if (record.getPosition() == maxRecord.getPosition()) {
상태를 가지는 객체의 데이터를 꺼내려(get)하지 말고 객체에 메시지를 보내라는 원칙에 따라 구현한다.

지금 구조와 maxRecord.matchPosition(record)와 같이 구현하는 것 중 어느 것이 나을까?

2018-04-03 02:33 UTC, javajigi commented on src/main/java/racingcar/interfaces/Car.java
>      String getName();
Record에 position과 name을 담고 있기 때문에 move 메소드만 있어도 되지 않을까?

2018-04-03 14:42 UTC, hello-sangsik commented on src/main/java/racingcar/interfaces/Car.java
>      String getName();
Record의 생성자에 Car 인스턴스를 사용하여 값을 넣어주는데 메소드가 불필요할까요?
아니면 인터페이스에서 삭제하고 구현클래스에서만 선언하라는 뜻인지 궁금합니다.

2018-04-03 23:25 UTC, merged