step1 구현 1
code-squad/java-racingcar pull request #223
Opened 2018-04-02 14:46 UTC by INHYUCK

step1 구현하였습니다. 늦어서 죄송합니다.

질문이 두가지 있습니다.

1. 테스트하기위해 프로덕션코드의 메소드의 접근제어자 private 되어있는것을 public으로 변경해도 괜찮나요?

2. 로직테스트를 위한 메소드 안에 또다른 메소드(랜덤숫자로 제어가 불가능한)가 있는경우 어떻게 테스트를 할 수 있을까요? 내부에 있는 메소드의 경우 랜덤숫자를 매개변수화하여 테스트 완료했습니다.

감사합니다.

2018-04-02 22:02 UTC, javajigi requested changes
핵심 로직 구현과 View 관련 로직을 분리하는 연습을 좀 더 하면 좋겠어요.

2018-04-02 22:02 UTC, javajigi commented on src/main/java/car/Main.java
> +        RacingGame game = new RacingGame();
변수를 사용하는 가장 가까운 곳에서 생성할 것을 추천..
이 경우 16라인 바로 다음.

2018-04-02 22:02 UTC, javajigi commented on src/main/java/car/RacingGame.java
> +
불필요하게 공백 라인을 만들지 않는다.
공백 라인을 뛰우는 것도 코드상에 문맥이 달라지는 부분에 의도를 가지고 뛰우면 좋겠다.

2018-04-02 22:02 UTC, javajigi commented on src/main/java/car/RacingGame.java
> +    public void tryOngoing(int[] carPositions, int k, int randomNumber) { //랜덤숫자에 따라 전진
random 값 테스트를 위해 random 값 생성과 사용을 분리한 것 👍 
테스트를 위해 메소드를 private에서 public으로 변경하기 보다 default(아마 접근 제어자도 없는 메소드)로 변경할 것을 추천

이와 같이 테스트할 경우 테스트 코드가 복잡해짐. 다음과 같이 구현하거나..

```
public int tryOngoing(int currentPosition, int randomNumber)
```

int position을 인스턴스 변수롤 가지는 Car 객체를 추가하는 것도 하나의 방법임.

2018-04-02 22:02 UTC, javajigi commented on src/main/java/car/RacingGame.java
> +        System.out.println("");
메소드가 두 가지 일을 하고 있음.
문자열 생성과 문자열 출력을 분리해 봄. 테스트할 부분을 찾아봄.

2018-04-02 22:02 UTC, javajigi commented on src/main/java/car/RacingGame.java
> +    }
핵심 로직을 구현하는 부분(상태 변경 등과 같은)과 View 로직(System.in을 통해 값 입력, System.out을 통해 값 출력)을 분리한다.
한 객체에 이 두 가지 로직이 같이 구현되어 있는 경우 추후 View가 되었을 때 핵심 로직을 구현하는 코드를 재사용할 수 없다.
또한 View에 종속되는 순간 테스트하기도 힘들다. 
이 연습은 웹 프로그래밍을 할 때 DB에 종속된 코드와 DB에 종속되지 않은 코드를 분리함으로써 테스트 가능하도록 구현하는 것과 같은 연습이다.

2018-04-03 16:05 UTC, INHYUCK commented on src/main/java/racingGame/Game.java
> +        for(int i=0; i<time; ++i) {
동일하게 n번 반복하는 두가지 메소드가 있다고 했을때 반복문 안에 같이 넣어주는것보다 기능이 다르므로 따로 분리하고 각각 n번씩 반복하게 하는것이 더 좋은가요?(or 더 객체지향적인건가요?)

2018-04-03 23:15 UTC, javajigi commented on src/main/java/racingGame/Game.java
> +        for(int i=0; i<time; ++i) {
기능이 다른 경우 분리하는 것이 맞아요. 단, 성능상 이슈가 된다면 추후 하나로 통합하는 것을 고려해 보면 됩니다. 그리고 객체지향과는 관련이 없고요. 메소드가 한가지 일만 하는 원칙을 따르는 겁니다.

2018-04-03 23:17 UTC, merged