Step1
code-squad/java-racingcar pull request #224
Opened 2018-04-02 16:21 UTC by makkaba

계산기 수정하고 
차 경주 step1 을 되는데까지 구현해봤습니다

2018-04-02 22:11 UTC, javajigi requested changes
도메인 로직 구현과 View 로직 구현을 분리해 보면 좋겠어요. 그럼 테스트도 가능한 부분이 많아질겁니다.

2018-04-02 22:11 UTC, javajigi commented on src/main/java/Calculator.java
> +            return left*right;
code convention 위반

2018-04-02 22:11 UTC, javajigi commented on src/main/java/Racing.java
> +    private int[] carPositions;
carPositions.length를 통해 numCar를 구할 수 있기 때문에 굳이 numCar를 인스턴스 변수로 구현하지 않아도 될 것 같아요.

인스턴스 변수가 너무 많다. 인스턴스 변수를 줄여본다.
객체지향 설계 원칙의 "규칙 7: 3개 이상의 인스턴스 변수를 가진 클래스를 쓰지 않는다." 원칙을 따라본다. 즉, 2개까지 허용한다.

2018-04-02 22:11 UTC, javajigi commented on src/main/java/Racing.java
> +        this.numCar = numCar;
set method 보다는 생성자를 활용한다.

2018-04-02 22:11 UTC, javajigi commented on src/main/java/Racing.java
> +    public void setNumCircuit(int numCircuit){
set method 보다는 생성자를 활용한다.

2018-04-02 22:11 UTC, javajigi commented on src/main/java/Racing.java
> +        return this.carPositions;
인스턴스 변수에 대한 setter, getter 메소드를 무조건 만들지 않는다. 정말 필요한 경우만 생성한다.

2018-04-02 22:11 UTC, javajigi commented on src/main/java/Racing.java
> +}
핵심 로직을 구현하는 부분(상태 변경 등과 같은)과 View 로직(System.in을 통해 값 입력, System.out을 통해 값 출력)을 분리한다.
한 객체에 이 두 가지 로직이 같이 구현되어 있는 경우 추후 View가 되었을 때 핵심 로직을 구현하는 코드를 재사용할 수 없다.
또한 View에 종속되는 순간 테스트하기도 힘들다. 
이 연습은 웹 프로그래밍을 할 때 DB에 종속된 코드와 DB에 종속되지 않은 코드를 분리함으로써 테스트 가능하도록 구현하는 것과 같은 연습이다.

2018-04-02 22:11 UTC, javajigi commented on src/main/java/Racing.java
> +
불필요하게 공백 라인을 만들지 않는다.
공백 라인을 뛰우는 것도 코드상에 문맥이 달라지는 부분에 의도를 가지고 뛰우면 좋겠다.

2018-04-02 22:11 UTC, javajigi commented on src/test/java/RacingTest.java
> +        System.setErr(new PrintStream(errContent));
UI 테스트까지 진행한 것은 👍

2018-04-03 12:56 UTC, makkaba commented on src/main/java/Calculator.java
> +            return left*right;
연산자와 변수 사이에 띄어쓰기 때문인가요?
일단 그렇게 알고 반영하였습니다.

2018-04-03 12:57 UTC, makkaba commented on src/main/java/Racing.java
> +    private int[] carPositions;
`numCircuit` 과 `carPositions`만 사용하도록 변경하였습니다.

2018-04-03 12:57 UTC, makkaba commented on src/main/java/Racing.java
> +        this.numCar = numCar;
생성자에서 세팅하도록 변경하였습니다.

2018-04-03 12:57 UTC, makkaba commented on src/main/java/Racing.java
> +    public void setNumCircuit(int numCircuit){
이것 역시 반영하였습니다.

2018-04-03 13:00 UTC, makkaba commented on src/main/java/Racing.java
> +        return this.carPositions;
setter 함수를 테스트하려면 getter함수가 있어야 하는 것 같아서 생성했었습니다.
setter함수는 어떻게 테스트를 하면 좋을까요?
현재는 setter를 모두 없애고 생성자를 사용하도록 변경했기 때문에 필요한 것만 빼놓고 지웠습니다 :)

2018-04-03 13:34 UTC, javajigi commented on src/main/java/Racing.java
> +        return this.carPositions;
보통 setter 메소드는 인스턴스 변수를 만들고 툴을 통해 자동으로 생성되기 때문에 굳이 테스트할 필요 없다고 생각해요.

2018-04-03 23:26 UTC, javajigi commented
도메인 로직과 View 로직을 구분하기 위해 다음과 같은 구조로 도전해 보면 어떨까요?

```
public static void main(String[] args) {
    int carNo = InputView.getCarNo();
    int tryNo = InputView.getTryNo();

    RacingGame racingGame = new RacingGame(carNo);
    for(int i = 0; i < tryNo; i++) {
        GameResult result = racingGame.move();
        ResultView.print(result);
    }
}
```

GameResult에 이동한 위치 정보가 포함되어 있고요. 이 위치 정보를 활용해 출력하는 구조로 구현해 보면 좋을 것 같아요.

위 코드에서 힌트를 얻어 본인의 코드에 개선할 부분이 있는지 검토해 보고 리팩토링 해보세요.

2018-04-04 13:25 UTC, makkaba commented
피드백 주신 것 여러가지 반영하고 , 뷰와 도메인 부분을 나눴는데 
테스트 코드를 못 쓰겠더라구요.
구조가 더 이상한 쪽으로 가고 있는지..

2018-04-04 14:36 UTC, merged