자동차 경주게임 2단계
code-squad/java-racingcar pull request #225
Opened 2018-04-02 16:56 UTC by ssosso

- 자동차 이름 입력 및 표시 추가
- 우승자 구하는 로직 구현

2018-04-03 02:02 UTC, ssosso commented
master로 pull request를 드려 중간에 branch로 변경하였는데 혹시 이상이 있을 수 있다면 reject 부탁드립니다. 재차 요청드리겠습니다.

2018-04-03 02:25 UTC, javajigi requested changes
이번 실습을 보면 codesquad에 merge한 step1을 rebase한 후 브랜치를 생성하지 않았네요. 이번 step은 지금 상태로 진행하는데요. 다음 step 진행할 때는 rebase하고 진행 부탁드려요.

2018-04-03 02:25 UTC, javajigi commented on src/main/java/racingcar/domain/Car.java
> +	public Car() {}
기본 생성자 필요한가?

2018-04-03 02:25 UTC, javajigi commented on src/main/java/racingcar/domain/RacingGame.java
> +	private List<Rule> rules = new ArrayList<>();
현재 Rule이 하나인데 굳이 List로 구현할 필요가 있을까?

2018-04-03 02:25 UTC, javajigi commented on src/main/java/racingcar/domain/RacingGame.java
> +	public RacingGame() {
생성자로 자동차 이름을 전달해 자동차를 초기화하도록 하면 어떨까?

2018-04-03 02:25 UTC, javajigi commented on src/main/java/racingcar/RacingGameApplication.java
> +		OutputView.showWinnerOuput(racingGame.getWinner());
로직이 크게 다르지는 않는데요.
다음과 같이 RacingGame의 결과를 별도의 클래스를 받아서 처리하면 어떨까요?

```
public static void main(String[] args) {
    String carNames = InputView.getCarNames();
    int tryNo = InputView.getTryNo();

    RacingGame racingGame = new RacingGame(carNames);
    GameResult result;
    for(int i = 0; i < tryNo; i++) {
        result = racingGame.move();
        ResultView.print(result);
    }
    ResultView.printWinner(result);
}
```

이렇게 구현하면 GameResult는 List<Car> 정보만 가지고 있으면 되고, 우승자에 관련한 로직은 GameResult에서 List<Car> 정보를 활용해 구현하면 어떨까요?

2018-04-03 02:54 UTC, ssosso commented on src/main/java/racingcar/domain/RacingGame.java
> +	private List<Rule> rules = new ArrayList<>();
확장성을 고려해서 만들었습니다. 룰이 1개라는 명확한 전제가 있다면 굳이 리스트로 구현할 필요는 없을 것 같습니다.

2018-04-03 11:16 UTC, ssosso commented
rebase 진행하고 브랜치 생성하였는데도 처음 master로 pull request를 날려서 그런지 commit내역에 지난 merge내역이 포함된 것 같습니다. (https://github.com/ssosso/java-racingcar/tree/ssosso를 보면 #211(지난 두번째 merge)까지 반영되어 있는 것을 보실 수 있습니다.) 추후에는 master에 요청드리지 않도록 조심하겠습니다^^

2018-04-03 11:42 UTC, ssosso commented
rebase 진행하고 브랜치 생성하였는데도 처음 master로 pull request를 날려서 그런지 commit내역에 지난 merge내역이 포함된 것 같습니다ㅠㅠ <sub>(https://github.com/ssosso/java-racingcar/tree/ssosso를 보면 #211(지난 두번째 merge)까지 반영되어 있는 것을 보실 수 있습니다.)</sub><br/>
추후에는 master에 요청드리지 않도록 조심하겠습니다^^

2018-04-03 11:49 UTC, javajigi requested changes
전체 구조에 대한 피드백은 없고요. 작은 피드백 몇개 남겼어요.

2018-04-03 11:49 UTC, javajigi commented on src/main/java/racingcar/domain/RacingGame.java
>  				.filter(car -> maxTripMeter == car.getTripMeter())
객체에게 묻지 말고 말하라.
즉, get을 통해 데이터를 꺼내지 말고 메시지를 보내라.

car.isMaxTripMeter(maxTripMeter)

객체 지향 연습의 1차 연습이라 메시지 남겨요.

2018-04-03 11:49 UTC, javajigi commented on src/main/java/racingcar/domain/RacingGame.java
> +			car.move(rule.getMoveMeterForReward());
기존 car.move(rule)과 같이 구현하는 것이 더 낫지 않을까요?

2018-04-03 11:49 UTC, javajigi commented on src/test/java/racingcar/domain/RacingGameTest.java
> +        RacingGame racingGame = new RacingGame(new String[]{"test1", "test2", "test3"});
new RacingGame("test1,test2,test3")과 같이 테스트 가능하도록 RacingGame 생성자 구조를 바꾸는 것은 어떤가요?

2018-04-04 05:07 UTC, ssosso commented
경주용차라고 생각하고 Car의 move메서드는 rule을 파라미터로 받을 수 있게 변경하였습니다. 피드백 감사드립니다!

2018-04-04 09:28 UTC, merged