자동차 경주 게임 1단계와 문자열 계산기 구현
code-squad/java-racingcar pull request #227
Opened 2018-04-03 09:57 UTC by ohahohah

- 자동차 경주 게임 1단계 구현
- 문자열 계산기 구현

2018-04-03 10:07 UTC, ohahohah commented
## 질문
- 자동차 경주게임 테스트하기 어려운 이유가 대체 뭘까요?ㅠ 객체의 상태를 바꾸는 것도 테스트를 하나하나 다 해봐야하나요?
- private method 테스트 방법
  - reflection에서 setAccessible(true) 으로 해서 테스트하거나 PowerMock같은  라이브러리를 사용하는 방법이 있는데 method 명을 하드코딩하게 되어서, 함수명 고칠때 테스트케이스가 자꾸 깨져서 귀찮습니다.
  - private method 는 아예 테스트하지 않거나 package 에서 접근가능하도록 method 범위를 수정하는게 맞나요?

2018-04-03 11:34 UTC, javajigi commented
@ohahohah 
https://www.slipp.net/questions/253 글이 힌트를 얻는데 도움이 될 것 같네요.

2018-04-03 11:40 UTC, javajigi requested changes
테스트 코드를 만들기 힘든 이유는 테스트하기 힘든 로직(random 값 생성, UI 입출력)과 도메인 로직 구현이 섞여 있기 때문이다. 이 둘을 분리하기 위해 노력해 본다.

2018-04-03 11:40 UTC, javajigi commented on src/main/java/com/ohahohah/step0/StringCalculator.java
> +
계산기 구현 👍

2018-04-03 11:40 UTC, javajigi commented on src/main/java/com/ohahohah/step01/Car.java
> +  public void stopOrGo() {
메소드 구조를 다음과 같이 바꾸면 어떨까요?

```
public int stopOrGo(int randomValue) {
}
```

2018-04-03 11:40 UTC, javajigi commented on src/main/java/com/ohahohah/step01/Car.java
> +    System.out.println();
이 메소드를 문자열 생성과 문자열 출력으로 나누면 문자열 생성에 대해 테스트 가능하지 않을까?

2018-04-03 11:40 UTC, javajigi commented on src/main/java/com/ohahohah/step01/Car.java
> +    if (ThreadLocalRandom.current().nextInt(0, 9 + 1) >= 4) {
random 값 생성과 로직 처리를 구분한다.
즉, 테스트 가능한 부분과 테스트하기 힘든 부분을 분리한 후 테스트 가능한 부분만 테스트한다.

2018-04-03 11:40 UTC, javajigi commented on src/main/java/com/ohahohah/step01/RacingCar.java
> +
도메인 로직과 View 로직을 구분하기 위해 다음과 같은 구조로 도전해 보면 어떨까요?

```
public static void main(String[] args) {
    int carNo = InputView.getCarNo();
    int tryNo = InputView.getTryNo();

    RacingGame racingGame = new RacingGame(carNo);
    for(int i = 0; i < tryNo; i++) {
        GameResult result = racingGame.move();
        ResultView.print(result);
    }
}
```

GameResult에 이동한 위치 정보가 포함되어 있고요. 이 위치 정보를 활용해 출력하는 구조로 구현해 보면 좋을 것 같아요.

위 코드에서 힌트를 얻어 본인의 코드에 개선할 부분이 있는지 검토해 보고 리팩토링 해보세요.

2018-04-04 13:50 UTC, ohahohah commented on src/main/java/com/ohahohah/step01/Car.java
> +  public void stopOrGo() {
반영했습니다.

2018-04-04 13:50 UTC, ohahohah commented on src/main/java/com/ohahohah/step01/Car.java
> +    System.out.println();
반영했습니다.

2018-04-04 13:50 UTC, ohahohah commented on src/main/java/com/ohahohah/step01/Car.java
> +    if (ThreadLocalRandom.current().nextInt(0, 9 + 1) >= 4) {
반영했습니다.

2018-04-05 06:54 UTC, ohahohah commented on src/main/java/com/ohahohah/step01/RacingCar.java
> +
도메인 로직과 View를 분리했습니다. 각 이동횟차마다 바로 정보를 출력하고, 전체 레이싱게임 위치정보는 저장하지 않습니다.  Car 객체에 저장되어 있는 자동차의 현재 위치정보를 사용합니다.

2018-04-05 08:29 UTC, merged