자동차 경주 2단계
code-squad/java-racingcar pull request #243
Opened 2018-04-05 17:10 UTC by jihazard

각 자동차에 이름을 부여할 수 있다. 전진하는 자동차를 출력할 때 자동차 이름을 같이 출력한다.
        자동차 이름은 쉼표(,)를 기준으로 구분한다.
        자동차 경주 게임을 완료한 후 누가 우승했는지를 알려준다. 우승자는 한명 이상일 수 있다

2018-04-05 22:04 UTC, javajigi requested changes
Winner를 구하는 로직을 View에 구현했는데요. 이렇게 구현하면 View가 변경되는 경우 중복이 발생합니다. 결과를 반환하는 새로운 객체를 추가하도록 피드백 남겨봤어요.

2018-04-05 22:04 UTC, javajigi commented on src/main/java/racingCar/Car.java
> +import org.omg.CORBA.PRIVATE_MEMBER;
사용하지 않는 import문

2018-04-05 22:04 UTC, javajigi commented on src/main/java/racingCar/InputView.java
>      private int carNumbers;
이 값이 필요한가요? carNames만 들고 다니면 되지 않을까요?

2018-04-05 22:04 UTC, javajigi commented on src/main/java/racingCar/Racing.java
> +    public List<Car> race(List names) {
List<String> names

2018-04-05 22:04 UTC, javajigi commented on src/main/java/racingCar/Racing.java
>          for (int carCount = 0; carCount < this.carNumbers; carCount++) {
foreach 구문으로 구현해 본다.

2018-04-05 22:04 UTC, javajigi commented on src/main/java/racingCar/Racing.java
>          for (int tryCount = 0; tryCount < this.time; tryCount++) {
car.move(makeRandomNumber());

자동차 이동 유무에 대한 판단을 Car 객체가 담당하도록 구현해본다.

2018-04-05 22:04 UTC, javajigi commented on src/main/java/racingCar/RacingCarMain.java
> +        List<Car> result = racingCar.race(inputView.getCarNames());
List<Car> result로 반환하지 말고 게임 결과를 저장하는 GameResult와 같은 객체에 List<Car>를 저장해 반환한다. winner 구하는 로직도 ResultView가 아니라 GameResult가 담당하도록 구현한다.

2018-04-06 23:11 UTC, javajigi requested changes
추가적으로 연습해 보면 좋겠다는 생각이 들어 피드백 남겨 봅니다.

2018-04-06 23:11 UTC, javajigi commented on src/main/java/racingCar/Winner.java
> +    private int winningCondition;
List<Car> results 인스턴스 변수만 남기고 나머지 인스턴스 변수 없이 구현해 본다.

2018-04-06 23:11 UTC, javajigi commented on src/main/java/racingCar/Winner.java
> +           if (winningCondition == car.getBar()) winner.add(car.getName());
상태를 가지는 객체의 데이터를 꺼내려(get)하지 말고 객체에 메시지를 보내라는 원칙에 따라 구현한다.

car.matchCondition(winningCondition)

현재 구현과 어떻게 다른가? 어떻게 구현하는 것이 좋을까?

2018-04-08 13:50 UTC, jihazard commented
추가로 피드백 남겨주신 부분 업데이트 해보았습니다 
접근 방법이 맞는지 모르겠습니다.

1. List results 인스턴스 변수만 남기고 나머지 인스턴스 변수 없이 구현해 본다.
2.상태를 가지는 객체의 데이터를 꺼내려(get)하지 말고 객체에 메시지를 보내라는 원칙에 따라 구현한다.

피드백 부탁드립니다.
감사합니다.

2018-04-09 03:41 UTC, merged