Step2 Solved
code-squad/java-racingcar pull request #244
Opened 2018-04-05 17:26 UTC by pnurep

step2 브랜치 새로 만들어 다시 pr 드립니다.

2018-04-05 22:20 UTC, javajigi requested changes
generic을 이중으로 사용하고 있어 코드의 복잡도가 많이 올라가는 것 같아요. 앞으로 이중 사용을 최대한 자제해 보세요.

2018-04-05 22:20 UTC, javajigi commented on src/main/java/racing/Game.java
> +            showWinners(drawCarsWithName(startRaceWithName(carNames, howMuchTimes)));
도메인 로직과 View 로직을 구분하기 위해 다음과 같은 구조로 도전해 보면 어떨까요?

```
public static void main(String[] args) {
    String carNames = InputView.getCarNames();
    int tryNo = InputView.getTryNo();

    RacingGame racingGame = new RacingGame(carNames);
    GameResult result;
    for(int i = 0; i < tryNo; i++) {
        result = racingGame.move();
        ResultView.print(result);
    }
    ResultView.printWinner(result);
}
```

이렇게 구현하면 GameResult는 List<Car> 정보만 가지고 있으면 되고, 우승자에 관련한 로직은 GameResult에서 List<Car> 정보를 활용해 구현하면 어떨까요?

2018-04-05 22:20 UTC, javajigi commented on src/main/java/racing/Racing.java
> +    }
이 클래스의 메소드들이 generic을 이중으로 사용하고 있어 코드를 읽고, 구현하는데 어려움이 있을 것 같아요. generic 사용을 하나만 사용하는 구조로 변경할 것을 추천해요.

List<HashMap<String, Integer>> => List<Car>와 같이 구현할 수도 있지 않을까요?

2018-04-06 06:58 UTC, pnurep commented on src/main/java/racing/Racing.java
> +    }
음.. 제네릭을 두번 쓰는게 권장되지 않는다는 것은 맞지만 이런 방식으로 구현을 제가 선호하는 편이라 저는 일단 이 방식대로 가겠습니다.

2018-04-06 16:21 UTC, closed without merging