step2 완료했습니다. 코드리뷰부탁드립니다.
code-squad/java-racingcar pull request #250
Opened 2018-04-06 10:44 UTC by devFrankle

안녕하세요? 교수님 step2 우선 완료했습니다. 코드 리뷰 부탁드립니다.

2018-04-06 10:54 UTC, javajigi requested changes
구현 잘 했네요. 단, 상태를 가지는 객체가 더 많은 일을 하도록 구현해 보면 좋을 것 같아요.

2018-04-06 10:54 UTC, javajigi commented on src/main/java/racingcar/domain/Car.java
> +    public void addCarPostion() {
random 값에 따른 이동 유무 판단을 Car가 담당하면 어떨까요?

`public void move(int randomValue)`와 같은 형태로..

2018-04-06 10:54 UTC, javajigi commented on src/main/java/racingcar/domain/GameResult.java
> +    private List<Car> winnerList = new ArrayList<>();
carList를 통해 winner의 목록을 구할 수 있는데 굳이 winnerList가 필요할까요?
이 인스턴스 없이 구현해 본다.

2018-04-06 10:54 UTC, javajigi commented on src/main/java/racingcar/domain/GameResult.java
> +    private List<Car> carList;
변수명과 메소드 이름에 List와 같은 자료구조 이름을 사용하는 것을 추천하지 않는다.
List와 같은 복수의 데이터의 경우 복수형을 쓰는 것이 더 적합하다.

2018-04-06 10:54 UTC, javajigi commented on src/main/java/racingcar/domain/RacingGame.java
> +    public static final int RULENUM = 4;
클래스의 구현 순서는 다음과 같다. 다음 원칙에 따라 구현한다.

```
class A {
    상수(static final) 또는 클래스 변수
    인스턴스 변수
    생성자
    메소드
}
```

2018-04-06 10:54 UTC, javajigi commented on src/main/java/racingcar/domain/GameResult.java
> +    }
winner를 구하는 로직이 RacingGame와 GameResult 중 어느 곳에 있는 것이 나을까?

2018-04-06 10:54 UTC, javajigi commented on src/main/java/racingcar/domain/RacingGame.java
> +        if(maxCarPosition == car.getCarPostion()) {
상태를 가지는 객체의 데이터를 꺼내려(get)하지 말고 객체에 메시지를 보내라는 원칙에 따라 구현한다.

`if (car.matchPosition(maxCarPosition))`과 같은 구현은?

2018-04-09 04:22 UTC, seogiee commented
교수님 안녕하세요? 피드백 주신거 반영해봤는데 레이싱 게임 2단계 코드리뷰 부탁드립니다. 감사합니다.

2018-04-09 04:56 UTC, merged