Step2 피드백 적용했습니다.
code-squad/java-racingcar pull request #256
Opened 2018-04-07 08:34 UTC by pnurep

2018-04-07 12:06 UTC, javajigi requested changes
객체 추출 연습을 하기 위한 피드백 하나 남겨봅니다.

2018-04-07 12:06 UTC, javajigi commented on src/main/java/racing/Racing.java
> +    public static List<Map<String, Integer>> startRaceWithName(String[] names, int times) {
Map 대신 Car 클래스를 추가해 구현해 보는 것은 어떨까요?

2018-04-09 05:52 UTC, javajigi requested changes
전체적인 구조에 대한 피드백을 남겨봤고요. Generic을 이중으로 사용하는 코드가 보이는데요. 이렇게 구현하다보니 로직이 복잡해 지는 것 같아요. Generic 사용을 한 단계만 허용하도록 구현하면 어떨까요?

2018-04-09 05:52 UTC, javajigi commented on src/main/java/racing/Car.java
> +    public void setPosition(int increase) {
외부에서 로직을 구현 후 set을 하기보다 이동 유무를 판단하는 다음과 같은 메소드를 추가하면 어떨까?

`public void move(int randomValue)`와 같이 random 값을 전달하는 구조.

2018-04-09 05:52 UTC, javajigi commented on src/main/java/racing/Game.java
도메인 로직과 View 로직을 구분하기 위해 다음과 같은 구조로 도전해 보면 어떨까요?

```
public static void main(String[] args) {
    String carNames = InputView.getCarNames();
    int tryNo = InputView.getTryNo();

    RacingGame racingGame = new RacingGame(carNames);
    GameResult result;
    for(int i = 0; i < tryNo; i++) {
        result = racingGame.move();
        ResultView.print(result);
    }
    ResultView.printWinner(result);
}
```

이렇게 구현하면 GameResult는 List<Car> 정보만 가지고 있으면 되고, 우승자에 관련한 로직은 GameResult에서 List<Car> 정보를 활용해 구현하면 어떨까요?

2018-04-09 06:25 UTC, pnurep commented on src/main/java/racing/Game.java
이미 GameResult 클래스가 말씀해주신대로 역할을 담당하고 있습니다.

2018-04-09 09:23 UTC, merged