Step2
code-squad/java-racingcar pull request #259
Opened 2018-04-08 12:00 UTC by jinhoyim

자동차 이름 기능
우승자 기능

2018-04-08 16:35 UTC, jinhoyim commented
웹 구현에 포지션 부분은 아직 못해서 숫자만 출력했습니다.
이 부분을 핸들바에 헬퍼로 구현하거나 position int 값으로 반복처리를 해보려고 했는데 잘 안되네요.
View 용 Car 모델을 만들어서 position 만큼 텍스트를 찍을 수 있게 만드는 방법만 떠오르네요.

2018-04-08 21:55 UTC, javajigi requested changes
View 용 Car 모델을 만들어서 position 만큼 텍스트를 찍을 수 있게 만드는 방법만 떠오르네요.
=> 현재는 이 정도 수준이면 충분할 것 같아요. 그리 중요한 부분은 아니니 생각한 데로 구현하세요.

step2, step3을 한번에 구현하셨네요. 코드 깔끔하게 잘 구현하셨네요. 💯

2018-04-08 21:55 UTC, javajigi commented on src/main/java/com/codesquad/carracing/domain/Car.java
> +        this("", 0);
이 생성자가 굳이 필요한가요?

2018-04-08 21:55 UTC, javajigi commented on src/main/java/com/codesquad/carracing/domain/CarRacing.java
> +        final String[] carNames = CarRacing.split(names, delimiter);
CarRacing.split한 이유는? 그냥 split해도 되지 않나요?

2018-04-09 00:11 UTC, jinhoyim commented on src/main/java/com/codesquad/carracing/domain/CarRacing.java
> +        final String[] carNames = CarRacing.split(names, delimiter);
구조를 바꾸다 잘못 남은 것 같습니다. 지우는게 맞는것 같아요.

2018-04-09 00:12 UTC, jinhoyim commented on src/main/java/com/codesquad/carracing/domain/Car.java
> +        this("", 0);
기본 생성자를 편하게 쓸수 있지 않을까 싶었는데 사실 생성자에서 기본값이 뭐가 들어가는지 확인하고 써야해서 더 불편한 느낌은 있었습니다. 지우는게 맞는것 같아요.

2018-04-09 21:40 UTC, merged