Step3
code-squad/java-racingcar pull request #272
Opened 2018-09-10 09:58 UTC by Sehun-Kim

step3입니다.

2018-09-11 01:03 UTC, javajigi requested changes
전체적으로 구현 잘 했네요. 👍 
피드백 좀 남겼으니 개선해 보세요.

2018-09-11 01:03 UTC, javajigi commented on src/main/java/racingcar/ResultView.java
> +}
pr 보낼 때 두번 연속 master 브랜치로 보냈는데요.
master 브랜치가 아니라 자신의 github id 브랜치로 보내야 합니다. 주의해 주세요.

2018-09-11 01:03 UTC, javajigi commented on src/main/java/racingcar/Car.java
> +        int randNum = random.nextInt(10);
값을 하드코딩하지 마라.
상수(static final)를 만들고 이름을 부여해 이 변수의 역할이 무엇인지 의도를 드러내라.

2018-09-11 01:03 UTC, javajigi commented on src/main/java/racingcar/Car.java
> +        if (randNum >= 4) this.position++;
값을 하드코딩하지 마라.
상수(static final)를 만들고 이름을 부여해 이 변수의 역할이 무엇인지 의도를 드러내라.

2018-09-11 01:03 UTC, javajigi commented on src/main/java/racingcar/InputView.java
> +        return carNamesArr;
로컬 변수가 필요 없으면 굳이 로컬 변수를 생성하지 마라

`return carNames.split(",");`와 같이 구현해 본다.

2018-09-11 01:03 UTC, javajigi commented on src/main/java/racingcar/InputView.java
> +        return input;
Scanner api 사용하면 좀 더 쉽게 구현할 수 있다.

2018-09-11 01:03 UTC, javajigi commented on src/main/java/racingcar/Main.java
>          race.run();
```
List<Car> cars = rac.run();
```

위와 같이 구현하는 것은 어떤까? 어떤 방식으로 구현하는 것이 더 나을까?

2018-09-11 01:03 UTC, javajigi commented on src/main/java/racingcar/Main.java
>          race.run();
time을 run() 메소드의 인자로 전달하는 것은 어떤가?
run(time);

2018-09-11 01:03 UTC, javajigi commented on src/main/java/racingcar/Racing.java
> +        for (int i = 0; i < carNames.length; i++) {
for문 말고 carNames 배열의 foreach 구문을 사용해 본다.
구글에서 "foreach array"로 검색해 본다.

2018-09-11 01:03 UTC, javajigi commented on src/main/java/racingcar/ResultView.java
> +            if (car.getPosition() == maxPosition) {
상태를 가지는 객체의 데이터를 꺼내려(get)하지 말고 객체에 메시지를 보내라는 원칙에 따라 구현한다.

2018-09-11 08:47 UTC, Sehun-Kim commented on src/main/java/racingcar/ResultView.java
> +}
넵 주의하겠습니다!ㅜ

2018-09-12 08:16 UTC, javajigi approved these changes
구현 잘 했네요. 작은 피드백 좀 남겼으니 4단계에서 적용해 보세요.

2018-09-12 08:16 UTC, javajigi commented on src/main/java/racingcar/Car.java
> +        return (this.position == maxPosition)? true : false;
`return this.position == maxPosition;`으로 구현 끝이지 않을까?

2018-09-12 08:16 UTC, javajigi commented on src/main/java/racingcar/InputView.java
> +
불필요하게 공백 라인을 만들지 않는다.
공백 라인을 뛰우는 것도 코드상에 문맥이 달라지는 부분에 의도를 가지고 뛰우면 좋겠다.

2018-09-12 08:16 UTC, javajigi commented on src/main/java/racingcar/InputView.java
불필요하게 공백 라인을 만들지 않는다.
공백 라인을 뛰우는 것도 코드상에 문맥이 달라지는 부분에 의도를 가지고 뛰우면 좋겠다.

2018-09-12 08:16 UTC, merged

2018-09-12 09:07 UTC, Sehun-Kim commented on src/main/java/racingcar/Car.java
> +        return (this.position == maxPosition)? true : false;
넵.. 바보같았습니다 ㅠ