step3 class division
code-squad/java-racingcar pull request #319
Opened 2018-09-13 14:19 UTC by gbeea1004

class division

2018-09-13 23:21 UTC, javajigi requested changes
구현하느라 고생했네요. 피드백 남겼어요

2018-09-13 23:21 UTC, javajigi commented on src/main/java/racingcar/Car.java
> +        for (int i = 0; i < count; i++) {
요구사항은 자동차 한대가 한번에 시도횟수 만큼 이동하는 것이 아님.
첫번째 시도 횟수에 모든 자동차 이동 여부 결정, 두번째 시도 횟수에 모든 자동차 이동 여부 결정과 같이 시도 횟수별로 모든 자동차의 이동 여부를 판단하는 구조

2018-09-13 23:21 UTC, javajigi commented on src/main/java/racingcar/InputView.java
> +    public String[] userName(){
클래스 메소드로 구현해 본다.

2018-09-13 23:21 UTC, javajigi commented on src/main/java/racingcar/InputView.java
> +    public int time() {
클래스 메소드로 구현해 본다.

2018-09-13 23:21 UTC, javajigi commented on src/main/java/racingcar/InputView.java
> +        return count;
로컬 변수 없이 `return s.nextInt();`와 같이 구현해 본다.

2018-09-13 23:21 UTC, javajigi commented on src/main/java/racingcar/InputView.java
> +        return nameArr;
로컬 변수를 최소화해 구현해 본다.

2018-09-13 23:21 UTC, javajigi commented on src/main/java/racingcar/RacingGame.java
> +
불필요하게 공백 라인을 만들지 않는다.
공백 라인을 뛰우는 것도 코드상에 문맥이 달라지는 부분에 의도를 가지고 뛰우면 좋겠다.

2018-09-13 23:21 UTC, javajigi commented on src/main/java/racingcar/Car.java
> +    public int position = 0;
인스턴스 변수는 특별한 이유는 없는 한 private으로 구현한다.
객체 외부에서 상태 값을 임의로 변경할 수 있도록 하는 것은 캡슐화 위반이다.

2018-09-13 23:21 UTC, javajigi commented on src/main/java/racingcar/Car.java
> +    public String name;
인스턴스 변수는 특별한 이유는 없는 한 private으로 구현한다.
객체 외부에서 상태 값을 임의로 변경할 수 있도록 하는 것은 캡슐화 위반이다.

2018-09-13 23:21 UTC, javajigi commented on src/main/java/racingcar/ResultView.java
> +    Car[] carArr;
carPositions, carArr 2개의 변수를 제거하고, 
ResultView의 모든 메소드를 클래스 메소드로 구현해 본다.

2018-09-14 04:41 UTC, javajigi requested changes
피드백 남겼어요.

2018-09-14 04:41 UTC, javajigi commented on src/main/java/racingcar/RacingGame.java
>  public class RacingGame {
Car[]을 RacingGame의 인스턴스 변수로 구현해 본다.

2018-09-14 04:41 UTC, javajigi commented on src/main/java/racingcar/RacingGame.java
> +    public static void main(String[] args) {
메소드가 너무 많은 일을 하고 있다. 다음 원칙을 지켜 메소드를 구현한다.

작게 만들어라. - 함수를 만드는 첫 번재 규칙은 '작게'다. 함수를 만드는 두 번째 규칙은 '더 작게'다.
한 가지만 해라. - 함수는 한 가지를 해야 한다. 그 한 가지를 잘 해야 한다. 그 한 가지만 해야 한다.

2018-09-14 04:41 UTC, javajigi commented on src/main/java/racingcar/ResultView.java
> +    public static void output(int [] carPos, Car[] carArr){
int [] carPos 인자 없이 Car[] 인자만으로 같은 기능을 구현해 본다.

2018-09-14 04:41 UTC, javajigi commented on src/main/java/racingcar/ResultView.java
> +        if(max <= carArr[i].getPosition()){
상태를 가지는 객체의 데이터를 꺼내려(get)하지 말고 객체에 메시지를 보내라는 원칙에 따라 구현한다.

carArr[i].getPosition()와 같이 값을 꺼내지 말고 Car 객체에 메시지를 보내 같은 로직을 구현해 본다.

2018-09-14 04:41 UTC, javajigi commented on src/main/java/racingcar/ResultView.java
> +        if(carArr[i].getPosition() == max){
상태를 가지는 객체의 데이터를 꺼내려(get)하지 말고 객체에 메시지를 보내라는 원칙에 따라 구현한다.

carArr[i].getPosition()와 같이 값을 꺼내지 말고 Car 객체에 메시지를 보내 같은 로직을 구현해 본다.

2018-09-14 06:12 UTC, gbeea1004 commented on src/main/java/racingcar/ResultView.java
> +        if(carArr[i].getPosition() == max){
만들어진 Car 배열 안에서 각각의 Position 값을 비교하는 것을 어떻게 값을 꺼내지 않고 로직을 구현해야하는지 잘 모르겠습니다..

2018-09-14 07:36 UTC, merged