Step1 구현
code-squad/java-racingcar pull request #75
Opened 2018-01-06 08:49 UTC by kineo2k

Step1 구현했습니다.
리뷰 부탁드려요 ^^

2018-01-06 10:35 UTC, javajigi requested changes
구현 잘 하셨네요. 연습 삼아 피드백 몇개 남겼어요.

2018-01-06 10:35 UTC, javajigi commented on src/main/java/com/mrblue/codesquad/javaracingcar/Car.java
> +public class Car {
모든 메소드를 public으로 두지 말고 최소한의 범위만 허용하도록 한다.

2018-01-06 10:35 UTC, javajigi commented on src/main/java/com/mrblue/codesquad/javaracingcar/Car.java
> +				 .ifPresent(this::printResult);
로직 구현하는 곳에서 View를 바로 호출하지 말고 둘을 분리한다.
이와 같이 구현할 경우 테스트하기 어려움.

2018-01-06 10:35 UTC, javajigi commented on src/main/java/com/mrblue/codesquad/javaracingcar/Car.java
> +		System.out.println(resultMessage);
View 로직을 별도의 클래스로 분리한다.

2018-01-12 09:11 UTC, kineo2k commented on src/main/java/com/mrblue/codesquad/javaracingcar/Car.java
> +public class Car {
시작이 늦었습니다 ^^;
가능한 모든 인터페이스를 private으로  수정했습니다.

2018-01-12 09:11 UTC, kineo2k commented on src/main/java/com/mrblue/codesquad/javaracingcar/Car.java
> +				 .ifPresent(this::printResult);
로직과 뷰 호출부를 분리했습니다.

2018-01-12 09:12 UTC, kineo2k commented on src/main/java/com/mrblue/codesquad/javaracingcar/Car.java
> +		System.out.println(resultMessage);
뷰로직을 별도 클래스로 분리했습니다.
간단한 출력 구문이라서 뷰라는 인지를 못하고 그냥 코딩 했네요.
많이 배웁니다 ^^

2018-01-12 10:34 UTC, merged