feat(step1) : RacingGame 기능 구현 및 테스트 작성
code-squad/java-racingcar pull request #83
Opened 2018-01-07 13:27 UTC by hY43

RacingGame, RacingGameTest, InputView, ResultView에 대한 기능 구현 및 테스트 작성하였습니다.

2018-01-08 02:50 UTC, javajigi requested changes
InputView는 View 역할만 하도록 구현해 보면 좋겠네요. 인스턴스 변수의 사용을 최소하하면 좋겠어요.

2018-01-08 02:50 UTC, javajigi commented on src/main/java/RacingGame/InputView.java
> +	private int[] carPositions;
이 값은 InputView에서 관리하는 것이 적합해 보이지 않네요.
다른 곳에서 관리하면 좋겠어요.

2018-01-08 02:50 UTC, javajigi commented on src/main/java/RacingGame/InputView.java
> +
다음과 같은 방식으로 구현하면 굳이 인스턴스 변수, getter 메소드를 추가하지 않아도 될 것 같아요.

```
public static int getCountOfCar(Scanner sc) {
    System.out.println("자동차 대수는 몇 대 인가요?");
    return sc.nextInt();
}
```

2018-01-08 02:50 UTC, javajigi commented on src/main/java/RacingGame/InputView.java
> +	public void setTime(int time) {
불필요한 setter/getter를 만드는 습관이 있는데요.
setter/getter 메소드는 정말 필요한 순간이 아니면 추가하지 말아 보세요.

2018-01-08 02:50 UTC, javajigi commented on src/main/java/RacingGame/RacingGame.java
> +	public int[] move() {
메소드 이름은 move인데 너무 많은 일을 하고 있네요.
move라면 자동차의 이동 기능만 구현하는 것이 맞을 것 같아요.

2018-01-08 02:50 UTC, javajigi commented on src/main/java/RacingGame/InputView.java
> +public class InputView {
InputView는 사용자의 입력을 받는 역할만 하면 좋겠어요.

2018-01-08 02:50 UTC, javajigi commented on src/main/java/RacingGame/RacingGame.java
> +public class RacingGame {
자동차의 이동 기능 구현과 같은 핵심 로직 구현은 Car와 같은 클래스를 추가해서 구현해 보세요.

2018-01-08 15:29 UTC, hY43 commented
refactor(step1) : Car Class 추가 및 기존 Class 수정

2018-01-09 05:11 UTC, javajigi requested changes
구현 잘하셨는데요. 제가 main method의 기본 뼈대를 제시해봤어요. 기존에 자신이 구현한 코드와 어떻게 달라지는지? 어떤 점에서 좋고, 나쁜지 비교해 보면 좋겠어요.

2018-01-09 05:11 UTC, javajigi commented on src/main/java/RacingGame/RacingGame.java
> +public class RacingGame {
main() 메소드를 다음과 같은 구조로 동작할 수 있도록 구현해 보세요.

```
public static void main(String[] args) {
  Scanner sc = new Scanner(System.in);
  int carCounts = InputView.getCountOfCar(sc);
  int time = InputView.getTimeOfMove(sc);

  RacingGame racingGame = new RacingGame(carCounts);
  List<Car> cars = racingGame.move(time);

  ResultView.printResult(cars);
}
```

RacingGame은 다음과 같이 자동차 목록을 가지도록 구현해 보고요.

```
public class RacingGame {
  private List<Car> cars;

  [...]
}
```

2018-01-09 15:50 UTC, hY43 commented
Main Method에 맞게 소스코드변경하였습니다.
이에 맞춰 수정하고 보니 기존에는 int 배열을 통해 자동차의 이동거리를 저장하긴 했지만 자동차 객체가 각각 움직이지 않고 자동차 객체들 전체가 한번에 움직이기 때문에 각 객체의 행동이 독립적이지 않았던 것 같습니다.
이 때문에 불필요한 인스턴스 변수와 메서드들이 생겨난 것 같습니다.

2018-01-10 01:14 UTC, javajigi requested changes
코드가 많이 깔끔해 졌네요. 조금 더 개선했으면 하는 바람으로 피드백 남겨요.

2018-01-10 01:14 UTC, javajigi commented on src/test/java/RacingGame/RacingGameTest.java
> +public class RacingGameTest {
이 테스트의 경우 RacingGameTest가 아니라 CarTest가 맞겠네요.

2018-01-10 01:14 UTC, javajigi commented on src/main/java/RacingGame/Car.java
> +    public int moveYn(int ranNum) {
바로 위의 movePosition과 이 메소드를 합쳐도 될 것 같아요.

```
public void move(int ranNum) {
  //
}
```

2018-01-10 01:14 UTC, javajigi commented on src/main/java/RacingGame/Car.java
> +    private enum GOYN{
굳이 enum까지 사용하는 건 과한 것 같아요.

2018-01-10 15:04 UTC, hY43 commented
feat(Step1) 
1. Car.java : enum 제거
2. Car.java : moveYn, movePosition 한개 메소드로 수정
3. CarTest.java : 테스트케이스 수정

2018-01-10 15:16 UTC, hY43 commented on src/main/java/RacingGame/Car.java
> +    public int moveYn(int ranNum) {
혹시 이 코드의 수정 이유가 굳이 외부에서 값을 계산하도록 하는게 아니라 객체에서 carPosition을 직접 이동시키도록 구현하기 위함인가요??

2018-01-11 03:15 UTC, merged