Step2
code-squad/java-racingcar pull request #86
Opened 2018-01-08 23:53 UTC by sooyoung32

2018-01-09 05:18 UTC, javajigi requested changes
비지니스 로직 구현 클래스와 UI 로직 구현 클래스를 분리한다.

2018-01-09 05:18 UTC, javajigi commented on src/main/java/racinggame/Car.java
> +    public Car(String name, int position) {
이 생성자를 제거하고 구현해 본다.
테스트도 가능해야함.

2018-01-09 05:18 UTC, javajigi commented on src/main/java/racinggame/Car.java
>      public void printResult() {
앞의 getResult() 메소드와 printResult() 메소드를 다른 클래스로 분리해서 구현해 본다.
어느 클래스로 어떻게 구현하는 것이 좋을지 고민해 본다.

2018-01-09 05:18 UTC, javajigi commented on src/main/java/racinggame/Racing.java
> +        int maxPosition = cars.stream().mapToInt(Car::getPosition).summaryStatistics().getMax();
구글에서 "java stream max value"로 검색해 더 간단한 방법을 찾는다.

2018-01-09 05:18 UTC, javajigi commented on src/main/java/racinggame/Racing.java
> +    public String getWinners() {
메소드는 3가지 일을 하고 있음.
메소드가 한 가지 일만 하도록 리팩토링 해본다.

2018-01-09 05:18 UTC, javajigi commented on src/main/java/racinggame/Racing.java
> +        return cars.stream().filter(car -> car.getPosition() == maxPosition).map(car -> car.getName()).collect(Collectors.joining(","));
`car.getPosition() == maxPosition` => `car.matchPosition(maxPosition)` 중 어떻게 구현하는 것이 좋을까에 대해 비교해 본다.

2018-01-09 05:18 UTC, javajigi commented on src/main/java/racinggame/Racing.java
>      public void racingResult() {
비지니스 로직 구현 클래스와 UI 관련 로직이 한 클래스에 위치함. 역할을 분리해 본다.

2018-01-10 01:08 UTC, javajigi requested changes
내 의도와는 달라서 이전 상태로 원복하는 단위 테스트 추가해 봤다. 이번에는 수정하면 바로 merge할께

2018-01-10 01:08 UTC, javajigi commented on src/test/java/racinggame/RacingTest.java
>          racing= new Racing(cars);
내가 의도한 것은 이게 아닌데..
이 상태라면 기존 생성자를 유지하고 다음과 같이 테스트 코드를 만들면 훨씬 깔끔할 것 같다.
앞으로 테스트 데이터 만들 때 Arrays.asList() 사용할 경우 많을 거다.

```
    @Before
    public void setUp() throws Exception {
        List<Car> cars = Arrays.asList(
            new Car("Sooyoung", 2),
            new Car("Test", 1), 
            new Car("Code", 2)
        );
        racing= new Racing(cars);
    }
```

나는 어떻게 접근했는지는 토요일 피드백할 때 공유할께.

2018-01-10 02:24 UTC, sooyoung32 commented on src/test/java/racinggame/RacingTest.java
>          racing= new Racing(cars);
어제 급하게 하다보니 의도를 생각하지 못하고 코딩한 것 같습니다. 일단 step3을 진행하기 위해 피드백 주신대로 수정하여 push 하였습니다. step3 진행하면서 좀 더 고민해 보도록 하겠습니다. 감사합니다!

2018-01-10 02:27 UTC, merged