Step1 [jimmy] 자동차 경주 1단계 마무리했습니다
code-squad/java-racingcar pull request #99
Opened 2018-01-10 07:11 UTC by jaeyeon93

자동차경주 1단계 일단 구현만 됩니다...

2018-01-10 07:51 UTC, javajigi requested changes
오호. 드디어 구현 완료.
피드백 남겼으니 리팩토링해 봐라.

2018-01-10 07:51 UTC, javajigi commented on .idea/checkstyle-idea.xml
> +<?xml version="1.0" encoding="UTF-8"?>
불필요한 파일들이 추가되고 있다.
.gitignore 파일에 ".idea/"를 추가해 디렉토리 삭제하고 gitignore 처리 해주면 좋겠다.

2018-01-10 07:51 UTC, javajigi commented on src/main/java/Racing.java
> +    public static void main (String args[]) {
구현잘 했다. 그런데 main 메소드가 너무 많은 일을 하고 있다.
main 메소드가 한 가지 일만 하도록 메소드를 분리해 본다.

2018-01-10 07:56 UTC, jaeyeon93 commented on src/main/java/Racing.java
> +    public static void main (String args[]) {
네 알겠습니다 :) 감사합니다 ㅎㅎ

2018-01-11 06:14 UTC, javajigi requested changes
인스턴스 변수 연습을 위한 피드백 하나 남겼다.

2018-01-11 06:14 UTC, javajigi commented on src/main/java/Racing.java
> +    public static void loop(int carnumber,int count){
인스턴스 변수를 연습하기 위해 다음과 같이 Car 클래스를 추가해 봐라.

```
public class Car {
  private int position;

  public void move(int randomValue) {
     // 로직 구현
  }
}
```

2018-01-11 06:41 UTC, jaeyeon93 commented on src/main/java/Racing.java
> +    public static void loop(int carnumber,int count){
네 알겠습니다 ㅎㅎ
피드백 감사합니다

2018-01-12 03:18 UTC, merged